services:
  - type: web
    name: react-app
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: REACT_APP_JSON_SERVER_URL
        value: json_server:3000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: private_service
    name: json-server
    env: docker
    dockerfilePath: ./Dockerfile.jsonserver
    envVars:
      - key: PORT
        value: '3000'